services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 3000:8080
    volumes:
      - ../:/app
    env_file: ../.env
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: weather_db
